version: "3"

services:
  hsd:
    container_name: hsd
    image: shalzz/hsd:2.3.0-208d1019
    # Volumes store your data between container upgrades
    volumes:
      - '/media/sda1/hsd-data:/root/.hsd'
    ports:
      - "54:54/tcp"
      - "54:54/udp"
      - "5300:5300/udp"
      - "5300:5300/tcp"
    command:
      - 'hsd'
      - '--plugins=handover'
      - '--ns-host'
      - '0.0.0.0'
      - '--ns-port'
      - '5300'
      - '--rs-host'
      - '0.0.0.0'
      - '--rs-port'
      - '54'
      - '--no-wallet'
      - '--listen'
    environment:
      - HSD_HANDOVER_INFURA_PROJECTID=
      - HSD_HANDOVER_INFURA_PROJECTSECRET=
    restart: unless-stopped
    healthcheck:
      test: dig @localhost www.ietf.org +dnssec
      interval: 1m
      timeout: 30s
      retries: 5
